// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CH.Toolbox
{

    public class Basic
    {

        [JsonProperty("phonetic")]
        public string Phonetic { get; set; }

        [JsonProperty("explains")]
        public string[] Explains { get; set; }
    }

}
