// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CH.Toolbox
{

    public class Web
    {

        [JsonProperty("value")]
        public string[] Value { get; set; }

        [JsonProperty("key")]
        public string Key { get; set; }
    }

}
